// Generated by https://quicktype.io
package types

// 分析器
type Proxy struct {
	GithubApi  string `json:"github-api"`
	GithubCors string `json:"github-cors"`
	GoogleAd   string `json:"google-ad"`
	GoogleAy   string `json:"google-ay"`
}

func (a *Proxy) SetProxy(api string, cors string, ad string, ay string) {
	a.GithubApi = api
	a.GithubCors = cors
	a.GoogleAd = ad
	a.GoogleAy = ay
}
