// Generated by https://quicktype.io
package types

// 分析器
type Sitemap struct {
	Domain    string `json:"domain"`
	Tls       string `json:"tls"`
	Cron      string `json:"cron"`
	Path      string `json:"path"`
	ExistFile string `json:"exist-file"`
}

func (a *Sitemap) SetSitemap(domain string, tls string, cron string, path string, existFile string) {
	a.Domain = domain
	a.Tls = tls
	a.Cron = cron
	a.Path = path
	a.ExistFile = existFile
}
